version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
  mongodb:
    container_name: recipes_app_db
    image: mongo:5.0.7
    ports:
      - 27017:27017
    environment:
      - MONGO_URI='mongodb://localhost:27017/RecipesApp'